class AsrErrorCode:
    MODEL_LOAD = "MODEL_LOAD"
    CHUNK_FAILED = "CHUNK_FAILED"
    CLOUD_AUTH = "CLOUD_AUTH"
    CLOUD_TIMEOUT = "CLOUD_TIMEOUT"
    CLOUD_QUOTA = "CLOUD_QUOTA"
    PREPROCESS_FAILED = "PREPROCESS_FAILED"
    DIARIZE_FAILED = "DIARIZE_FAILED"
