"""Generate a Swedish sentiment test set and save it as CSV.

Run once: python scripts/generate_testset.py
"""
from __future__ import annotations

import csv
import os

TEST_DATA: list[tuple[str, str]] = [
    # === POSITIVA ===
    ("Jag älskar verkligen den här produkten!", "positiv"),
    ("Det här är det bästa jag någonsin upplevt.", "positiv"),
    ("Fantastiskt bra service, rekommenderas varmt!", "positiv"),
    ("Vilken underbar dag det är idag!", "positiv"),
    ("Personalen var otroligt trevlig och hjälpsam.", "positiv"),
    ("Maten var utsökt och stämningen perfekt.", "positiv"),
    ("Jag är så nöjd med mitt köp!", "positiv"),
    ("Detta är verkligen toppen, tack så mycket!", "positiv"),
    ("Äntligen fick jag det jag väntat på!", "positiv"),
    ("Så glad att jag valde just denna tjänst.", "positiv"),
    ("Leveransen kom snabbare än förväntat, supernöjd!", "positiv"),
    ("Priset var mycket bra för den kvaliteten.", "positiv"),
    ("Jag kan verkligen rekommendera detta företag.", "positiv"),
    ("Allting fungerade precis som det skulle.", "positiv"),
    ("Kvaliteten överträffade mina förväntningar.", "positiv"),
    ("Tack för ett utmärkt bemötande!", "positiv"),
    ("Den bästa investeringen jag gjort på länge.", "positiv"),
    ("Jag är imponerad av hur snabbt det gick.", "positiv"),
    ("En fantastisk upplevelse från början till slut.", "positiv"),
    ("Helt klart värt varenda krona.", "positiv"),
    ("Supporten löste mitt problem på några minuter.", "positiv"),
    ("Jag har aldrig varit så här nöjd förut.", "positiv"),
    ("Väldigt professionellt och trevligt bemötande.", "positiv"),
    ("Kunden i fokus, det märks verkligen.", "positiv"),
    ("Jag ser fram emot att handla här igen.", "positiv"),
    ("Det här var precis vad jag behövde!", "positiv"),
    ("Så skönt att allting löste sig till slut.", "positiv"),
    ("En mycket positiv upplevelse överlag.", "positiv"),
    ("Produkten håller högsta kvalitet.", "positiv"),
    ("Det här är guld värt för mig.", "positiv"),
    ("Bästa beslutet jag tagit på länge!", "positiv"),
    ("Jag är så tacksam för hjälpen jag fick.", "positiv"),
    ("Fantastisk respons från kundtjänst!", "positiv"),
    ("Kan inte vara mer nöjd än så här.", "positiv"),
    ("Ett föredöme inom branschen!", "positiv"),
    ("Jag är helt såld på den här tjänsten.", "positiv"),
    ("Snabbt, smidigt och problemfritt.", "positiv"),
    ("Det märks att de bryr sig om sina kunder.", "positiv"),
    ("Bättre än jag någonsin kunnat föreställa mig.", "positiv"),
    ("Tio av tio, helt perfekt!", "positiv"),
    ("Är så himla glad just nu!", "positiv"),
    ("Lösningen var enkel och fungerar klockrent.", "positiv"),
    ("Allt gick smidigare än väntat.", "positiv"),
    ("En riktigt bra tjänst som jag använder dagligen.", "positiv"),
    ("Jag är stolt över att vara kund här.", "positiv"),
    ("Det känns tryggt och säkert att handla här.", "positiv"),
    ("Absolut bäst i klassen!", "positiv"),
    ("Kan varmt rekommendera till alla.", "positiv"),
    ("Överträffade alla mina förväntningar.", "positiv"),
    ("Jag är så imponerad av resultatet!", "positiv"),
    ("Suverän kvalitet till ett rimligt pris.", "positiv"),
    ("Är så glad att jag hittade den här tjänsten.", "positiv"),
    ("Lätt den bästa upplevelsen jag haft!", "positiv"),
    ("Det är en fröjd att använda er tjänst.", "positiv"),
    ("Vilket fantastiskt team ni har!", "positiv"),
    ("Har aldrig känt mig så väl omhändertagen.", "positiv"),
    ("Oslagbar service, tack för allt!", "positiv"),
    ("Enormt nöjd med hela processen.", "positiv"),
    ("Det här förändrade verkligen min vardag.", "positiv"),
    ("Grymt bra jobbat av hela teamet!", "positiv"),
    ("Prisvärt, snabbt och framförallt bra kvalitet.", "positiv"),
    ("Jag är så glad att jag valde er.", "positiv"),
    ("Perfekt lösning för mina behov.", "positiv"),
    ("Kan inte tänka mig ett bättre alternativ.", "positiv"),
    ("Helt outstanding jämfört med konkurrenterna.", "positiv"),
    ("En pärla i branschen!", "positiv"),
    ("Ni har verkligen överträffat er själva.", "positiv"),
    ("Så här ska kundservice se ut!", "positiv"),
    ("Jag är kund för livet nu.", "positiv"),
    ("Fantastiskt initiativ och genomförande.", "positiv"),
    # === NEUTRALA ===
    ("Jag har precis fått paketet och ska öppna det snart.", "neutral"),
    ("Produkten anlände idag enligt plan.", "neutral"),
    ("Jag ska testa den här veckan och återkomma.", "neutral"),
    ("Beställningen är gjord, väntar på leverans.", "neutral"),
    ("Har inte hunnit testa ännu, återkommer senare.", "neutral"),
    ("Paketet kom fram i tid som utlovat.", "neutral"),
    ("Jag köpte den här för ett par dagar sedan.", "neutral"),
    ("Min granne rekommenderade denna tjänst.", "neutral"),
    ("Det är en helt okej produkt för priset.", "neutral"),
    ("Jag fick information om leveransen via mail.", "neutral"),
    ("Det är varken bra eller dåligt, fungerar som förväntat.", "neutral"),
    ("Jag har använt tjänsten i ungefär en vecka nu.", "neutral"),
    ("Beställde i måndags, fick den på onsdagen.", "neutral"),
    ("Ska jämföra med andra alternativ innan jag bestämmer mig.", "neutral"),
    ("Det här är min första erfarenhet med företaget.", "neutral"),
    ("Har läst recensionerna men vill prova själv.", "neutral"),
    ("Fungerar precis som beskrivet på hemsidan.", "neutral"),
    ("Det är standard, inget speciellt men fungerar.", "neutral"),
    ("Jag väntar på att se hur det utvecklar sig.", "neutral"),
    ("Produkten ser ut som på bilderna.", "neutral"),
    ("Jag har inte märkt någon större skillnad än.", "neutral"),
    ("Ska ge det lite mer tid innan jag utvärderar.", "neutral"),
    ("Det är en blandad upplevelse hittills.", "neutral"),
    ("Behöver mer tid för att bilda mig en uppfattning.", "neutral"),
    ("Fick det jag beställde, varken mer eller mindre.", "neutral"),
    ("Leveranstiden var ungefär som förväntat.", "neutral"),
    ("Har precis installerat, ska testa nu.", "neutral"),
    ("Jag är varken imponerad eller besviken.", "neutral"),
    ("Det får duga tills vidare.", "neutral"),
    ("Priset är marknadsmässigt, inget extraordinärt.", "neutral"),
    ("Jag har kontaktat support för mer information.", "neutral"),
    ("Produkten gör vad den ska, inget mer.", "neutral"),
    ("Har inte hunnit bilda mig en uppfattning än.", "neutral"),
    ("Får se hur det fungerar på sikt.", "neutral"),
    ("Jag jämför fortfarande olika alternativ.", "neutral"),
    ("Standardutförande, inget anmärkningsvärt.", "neutral"),
    ("Ska återkomma med en mer detaljerad recension.", "neutral"),
    ("Det är godkänt men inget utöver det vanliga.", "neutral"),
    ("Paketet var helt och rent vid ankomst.", "neutral"),
    ("Har använt det några gånger, verkar fungera.", "neutral"),
    ("Gör det den ska, varken mer eller mindre.", "neutral"),
    ("Inget speciellt att anmärka på.", "neutral"),
    ("Betalningen gick igenom utan problem.", "neutral"),
    ("Fick bekräftelse direkt efter beställning.", "neutral"),
    ("Leveransen kom inom utsatt tid.", "neutral"),
    ("Användarmanualen var tydlig och enkel att följa.", "neutral"),
    ("Produkten var förpackad på ett säkert sätt.", "neutral"),
    ("Har inte behövt kontakta supporten ännu.", "neutral"),
    ("Jag är ny användare och lär mig fortfarande.", "neutral"),
    ("Har bara använt den ett par gånger hittills.", "neutral"),
    ("Jag har varken positiva eller negativa känslor.", "neutral"),
    ("Det är en helt vanlig produkt i sin kategori.", "neutral"),
    ("Ska utvärdera efter en månads användning.", "neutral"),
    ("Helt OK för det priset.", "neutral"),
    ("Har inte stött på några problem än så länge.", "neutral"),
    ("Får avvakta och se hur supporten hanterar ärendet.", "neutral"),
    ("Jag har precis påbörjat processen.", "neutral"),
    ("Återkommer när jag har mer erfarenhet.", "neutral"),
    ("Gjorde en beställning och fick orderbekräftelse.", "neutral"),
    ("Är i startfasen av att använda produkten.", "neutral"),
    ("Den fungerar men jag hade kanske förväntat mig mer.", "neutral"),
    ("Inget att klaga på men inget att hylla heller.", "neutral"),
    ("Jag registrerade mig och fick ett välkomstmail.", "neutral"),
    ("Det verkar vara en helt vanlig tjänst.", "neutral"),
    ("Ska ge det en ärlig chans innan jag dömer.", "neutral"),
    ("Fick hjälp med mitt ärende, väntar på lösning.", "neutral"),
    ("Jag har bara använt gratisdelen hittills.", "neutral"),
    ("Har precis skickat in min ansökan.", "neutral"),
    ("En kollega tipsade mig om den här tjänsten.", "neutral"),
    ("Det finns både fördelar och nackdelar.", "neutral"),
    # === NEGATIVA ===
    ("Jag är extremt besviken på den här produkten.", "negativ"),
    ("Det här är det sämsta jag någonsin köpt.", "negativ"),
    ("Vilken katastrof, allting gick fel!", "negativ"),
    ("Servicen var under all kritik.", "negativ"),
    ("Produkten gick sönder efter bara en vecka.", "negativ"),
    ("Jag ångrar verkligen att jag köpte den här.", "negativ"),
    ("Kundtjänsten var helt värdelös och otrevlig.", "negativ"),
    ("Hemskt bemötande, kommer aldrig tillbaka.", "negativ"),
    ("Slöseri med pengar, fungerar inte alls.", "negativ"),
    ("Det här var verkligen botten, uselt!", "negativ"),
    ("Leveransen var försenad med två veckor.", "negativ"),
    ("Paketet kom fram helt trasigt.", "negativ"),
    ("Fruktansvärt dålig kvalitet på materialet.", "negativ"),
    ("Jag är så arg och frustrerad över detta.", "negativ"),
    ("Kommer aldrig att rekommendera detta till någon.", "negativ"),
    ("Varning för detta företag, de lurar sina kunder.", "negativ"),
    ("Det här är rena rama skämtet.", "negativ"),
    ("Så otroligt dåligt hanterat från början till slut.", "negativ"),
    ("Totalt oacceptabelt bemötande från personalen.", "negativ"),
    ("Jag känner mig lurad och bedragen.", "negativ"),
    ("Hade höga förväntningar men blev djupt besviken.", "negativ"),
    ("Kvaliteten är usel, priset alldeles för högt.", "negativ"),
    ("Fruktansvärd upplevelse, undvik detta företag!", "negativ"),
    ("Supporten svarar inte på flera dagar.", "negativ"),
    ("Produkten fungerar inte som utlovat i reklamen.", "negativ"),
    ("Jag har aldrig varit med om sämre service.", "negativ"),
    ("Det känns som att jag blivit grundlurad.", "negativ"),
    ("Katastrofdålig produkt, pengarna tillbaka tack!", "negativ"),
    ("Hemsidan är helt omöjlig att navigera.", "negativ"),
    ("Värsta köpet jag gjort i hela mitt liv.", "negativ"),
    ("Skulle ge noll stjärnor om jag kunde.", "negativ"),
    ("Skandal att de får fortsätta sälja detta.", "negativ"),
    ("Blev felaktigt debiterad och ingen hjälp finns.", "negativ"),
    ("Helt meningslös produkt, gör ingenting.", "negativ"),
    ("Känner mig så frustrerad och maktlös.", "negativ"),
    ("Detta är oacceptabelt på alla sätt och vis.", "negativ"),
    ("Enorm besvikelse från ett så stort företag.", "negativ"),
    ("Sämsta investeringen någonsin.", "negativ"),
    ("Kommer aldrig mer handla här.", "negativ"),
    ("Skulle inte ens ge bort detta gratis.", "negativ"),
    ("Det här var droppen som fick bägaren att rinna över.", "negativ"),
    ("Helt bedrövligt, både produkt och service.", "negativ"),
    ("Har försökt få hjälp i en månad utan resultat.", "negativ"),
    ("Riktigt dåligt skick när det kom fram.", "negativ"),
    ("Vägrar ta ansvar för sina misstag.", "negativ"),
    ("Jag är helt förkrossad över hur dåligt det är.", "negativ"),
    ("Bottennapp, sämsta tänkbara upplevelse.", "negativ"),
    ("Kvaliteten är en ren skam för branschen.", "negativ"),
    ("Det här är inget annat än ett bedrägeri.", "negativ"),
    ("Fruktansvärt otrevlig och oprofessionell personal.", "negativ"),
    ("Vill varna alla för detta blufföretag.", "negativ"),
    ("Inte ens värt en enda krona.", "negativ"),
    ("Så fruktansvärt dåligt att jag saknar ord.", "negativ"),
    ("Skäms över att ha lagt pengar på detta.", "negativ"),
    ("Helt odugligt, inget fungerar som det ska.", "negativ"),
    ("En ren mardröm från start till mål.", "negativ"),
    ("Såg fram emot detta men det blev en total flopp.", "negativ"),
    ("Det är bedrövligt att de behandlar kunder så här.", "negativ"),
    ("Jag är så otroligt missnöjd med allting.", "negativ"),
    ("Känner mig totalt ignorerad av kundtjänst.", "negativ"),
    ("Oprofessionellt, oseriöst och direkt otrevligt.", "negativ"),
    ("Sämsta tänkbara kundupplevelsen.", "negativ"),
    ("Det finns inget positivt att säga om detta.", "negativ"),
    ("Ett stort skämt, undvik till varje pris.", "negativ"),
    ("Har aldrig blivit så illa behandlad förut.", "negativ"),
    ("Helt värdelöst, slösa inte dina pengar här.", "negativ"),
    ("Ren katastrof, ångrar allt.", "negativ"),
    ("Det här är bara sorgligt.", "negativ"),
    ("Totalt misslyckande från deras sida.", "negativ"),
    ("Vilken mardröm, hoppas ingen annan råkar ut för detta.", "negativ"),
]


def main() -> None:
    out_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "test_swedish.csv")
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["text", "label", "source"])
        for text, label in TEST_DATA:
            writer.writerow([text, label, "generated"])
    print(f"Test set written: {out_path} ({len(TEST_DATA)} samples)")
    pos = sum(1 for _, lbl in TEST_DATA if lbl == "positiv")
    neu = sum(1 for _, lbl in TEST_DATA if lbl == "neutral")
    neg = sum(1 for _, lbl in TEST_DATA if lbl == "negativ")
    print(f"  Distribution: {pos} positive, {neu} neutral, {neg} negative")


if __name__ == "__main__":
    main()
